---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.5

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

suites:
  - name: default
    run_list:
      - recipe[tomcat]
    attributes:
    data_bags_path: "test/integration/default/data_bags"

clusters:
  default:
    - default
