---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: "latest"

platforms:
- name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[tomcat]
    attributes:
    data_bags_path: "test/integration/default/data_bags"

  - name: tomcat55
    run_list:
      - recipe[tomcat]
    attributes: {
      tomcat: { version: '55' }
    }
    data_bags_path: "test/integration/default/data_bags"

clusters:
  default:
    - default
