#
# Cookbook specific settings
#
default[:tomcat][:ajp_connection_timeout] = 20000
default[:tomcat][:ajp_max_threads] = 200
default[:tomcat][:http_uri_encoding] = 'UTF-8'
default[:tomcat][:http_connection_timeout] = 20000
default[:tomcat][:prefix_dir] = '/usr/local'
default[:tomcat][:pid_dir] = '/var/run/tomcat'
default[:tomcat][:lock_dir] = '/var/lock/subsys'

#
# Start of Opscode compatible settings
#
default[:tomcat][:base_version] = '7'
default[:tomcat][:user] = 'tomcat'
default[:tomcat][:group] = 'tomcat'

default[:tomcat][:port] = 8080
default[:tomcat][:proxy_port] = nil

# Directories and files
default[:tomcat][:home] = "#{node[:tomcat][:prefix_dir]}/tomcat"
default[:tomcat][:base] = "#{node[:tomcat][:prefix_dir]}/tomcat"
default[:tomcat][:config_dir] = "#{node[:tomcat][:home]}/conf"
default[:tomcat][:log_dir] = "#{node[:tomcat][:home]}/logs"
default[:tomcat][:tmp_dir] = "#{node[:tomcat][:home]}/temp"
default[:tomcat][:work_dir] = "#{node[:tomcat][:home]}/work"
default[:tomcat][:context_dir] = "#{node[:tomcat][:config_dir]}/Catalina/localhost"
default[:tomcat][:webapp_dir] = "#{node[:tomcat][:home]}/webapps"
# Not used yet
default[:tomcat][:lib_dir] = "#{node[:tomcat][:home]}/lib"
default[:tomcat][:endorsed_dir] = "#{node[:tomcat][:lib_dir]}/endorsed"
#
# End of Opscode compatible settings
#

#
# Start of Opscode tomcat unsupported [yet] settings
#
default[:tomcat][:keytool] = 'keytool'
# TODO: SSL with key generation (nil will skip the whole ssl part of tomcat)
default[:tomcat][:ssl_port] = nil
#default[:tomcat][:ssl_port] = 8443
default[:tomcat][:ssl_proxy_port] = nil
default[:tomcat][:ajp_port] = 8009
default[:tomcat][:max_threads] = 200
default[:tomcat][:catalina_options] = ''
default[:tomcat][:java_options] = '-Xmx128M -Djava.awt.headless=true'
default[:tomcat][:use_security_manager] = false
default[:tomcat][:authbind] = 'no'
default[:tomcat][:ssl_max_threads] = 150
default[:tomcat][:ssl_cert_file] = nil
default[:tomcat][:ssl_key_file] = nil
default[:tomcat][:ssl_chain_files] = []
default[:tomcat][:keystore_file] = 'keystore.jks'
default[:tomcat][:keystore_type] = 'jks'
# The keystore and truststore passwords will be generated by the
# openssl cookbook's secure_password method in the recipe if they are
# not otherwise set. Do not hardcode passwords in the cookbook.
# default["tomcat"]["keystore_password"] = nil
# default["tomcat"]["truststore_password"] = nil
default[:tomcat][:truststore_file] = nil
default[:tomcat][:truststore_type] = 'jks'
default[:tomcat][:certificate_dn] = 'cn=localhost'
default[:tomcat][:deploy_manager_apps] = true
default[:tomcat][:loglevel] = 'INFO'
default[:tomcat][:tomcat_auth] = 'true'
##
# End of Opscode tomcat unsupported [yet] settings
##

default[:tomcat][:service] = "tomcat#{node[:tomcat][:base_version]}"
# Tomcat binaries and sha256 checksums
case node[:tomcat][:base_version]
when '7'
  default[:tomcat][:url] = 'http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.47/bin/apache-tomcat-7.0.47.tar.gz'
  default[:tomcat][:checksum] = '46dc31b08c120ffc2e38dccc119b9df02662a9fb297fa3fc6d90902c2f86057a'
when '6'
  default[:tomcat][:url] = 'http://archive.apache.org/dist/tomcat/tomcat-6/v6.0.37/bin/apache-tomcat-6.0.37.tar.gz'
  default[:tomcat][:checksum] = '3e91abc752bf2b6ca19df9c8644bccdd92ba837397a8c1a745d72f58d5301b00'
end
